import React, { useEffect, useState } from "react";
import { CheckCircle2, Loader2, Store } from "lucide-react";
import { api } from "./api";
import { C, FD, FB } from "./theme";

const inp = { background: C.card, border: `1px solid ${C.line}`, color: C.ink };
export default function AcknowledgmentPage({ acknowledgmentKey }) {
  const [data, setData] = useState(null); const [answers, setAnswers] = useState({}); const [busy, setBusy] = useState(false); const [done, setDone] = useState(false); const [error, setError] = useState("");
  useEffect(() => { api.getPublicQuestions(acknowledgmentKey).then(setData).catch((err) => setError(err.message)); }, [acknowledgmentKey]);
  const answered = (question) => { const value = answers[question.id]; if (question.type === "comment") return Boolean(value?.comment?.trim()); if (question.type === "yes_no" || question.type === "yes_no_comment") return Boolean(value?.answer); return Boolean(value); };
  const submit = async () => { if (!data) return; const questions = data.template.config.questions || []; if (questions.some((question) => !answered(question))) return setError("Please complete every question before submitting."); setBusy(true); try { await api.submitPublicQuestions(acknowledgmentKey, answers); setDone(true); } catch (err) { setError(err.message); } finally { setBusy(false); } };
  if (done || data?.acknowledged) return <div style={{ background: C.paper, minHeight: "100vh", fontFamily: FB }} className="flex items-center justify-center p-5"><div style={{ background: C.card, border: `1px solid ${C.line}`, maxWidth: 520 }} className="rounded-2xl p-8 text-center"><CheckCircle2 size={46} color={C.pine} className="mx-auto mb-3" /><h1 style={{ fontFamily: FD }} className="text-[25px] font-semibold">Acknowledgment received</h1><p style={{ color: C.sub }} className="mt-2 text-[14px]">Thank you. Your market team can now see your completed acknowledgment.</p></div></div>;
  if (!data && !error) return <div style={{ background: C.paper, minHeight: "100vh", color: C.sub }} className="flex items-center justify-center"><Loader2 size={18} className="animate-spin" /></div>;
  if (!data) return <div style={{ background: C.paper, minHeight: "100vh" }} className="flex items-center justify-center p-5"><p style={{ color: C.danger }} className="text-[14px]">{error}</p></div>;
  const questions = data.template.config.questions || [];
  return <div style={{ background: C.paper, minHeight: "100vh", fontFamily: FB, color: C.ink }} className="py-8 px-4"><main style={{ maxWidth: 680, margin: "0 auto" }}><div className="text-center mb-7"><div style={{ background: C.pine }} className="w-11 h-11 rounded-xl inline-flex items-center justify-center mb-3"><Store size={22} color={C.honey} /></div><h1 style={{ fontFamily: FD }} className="text-[28px] font-semibold">Vendor acknowledgment</h1><p style={{ color: C.sub }} className="text-[13px] mt-1">{data.approval.business_name} · {data.approval.market_name} · {data.approval.event_date}</p></div><section style={{ background: C.card, border: `1px solid ${C.line}` }} className="rounded-2xl p-5 sm:p-7"><p style={{ color: C.sub }} className="text-[13px] mb-4">Please read every item and provide the requested response.</p>{error && <p style={{ background: C.dangerSoft, color: C.danger }} className="rounded-lg px-3 py-2 text-[12.5px] mb-3">{error}</p>}<div className="flex flex-col gap-3">{questions.map((question, index) => <div key={question.id} style={{ background: C.paper2, border: `1px solid ${C.line}` }} className="rounded-xl p-4"><p className="text-[13.5px] font-bold">{index + 1}. {question.label}</p>{question.type === "acknowledgment" ? <label style={{ color: C.sub }} className="mt-2 text-[12px] flex gap-2 items-center"><input type="checkbox" checked={Boolean(answers[question.id])} onChange={(event) => setAnswers((current) => ({ ...current, [question.id]: event.target.checked }))} /> I have read and acknowledge this item.</label> : <div className="mt-3 flex flex-col gap-2">{question.type !== "comment" && <select value={answers[question.id]?.answer || ""} onChange={(event) => setAnswers((current) => ({ ...current, [question.id]: { ...(current[question.id] || {}), answer: event.target.value } }))} style={inp} className="px-3 py-2 rounded-lg text-[13px]"><option value="">Choose your response…</option><option value="yes">Yes</option><option value="no">No</option>{question.type === "yes_no_comment" && <option value="comment">Add a comment</option>}</select>}{(question.type === "comment" || answers[question.id]?.answer === "comment") && <textarea value={answers[question.id]?.comment || ""} onChange={(event) => setAnswers((current) => ({ ...current, [question.id]: { ...(current[question.id] || {}), comment: event.target.value } }))} rows={3} placeholder="Add your comment" style={inp} className="px-3 py-2 rounded-lg text-[13px] resize-y" />}</div>}</div>)}</div><button onClick={submit} disabled={busy} style={{ background: C.pine, color: "#fff", opacity: busy ? .65 : 1 }} className="mt-5 w-full py-3 rounded-lg text-[14px] font-bold">{busy ? "Submitting…" : "Submit acknowledgment"}</button></section></main></div>;
}
