import React, { useEffect, useState } from "react";
import { CheckCircle2, Copy, ExternalLink, Loader2, Send } from "lucide-react";
import { api } from "./api";
import { C, FD } from "./theme";

const inp = { background: C.card, border: `1px solid ${C.line}`, color: C.ink };
export default function EventQuestions({ dateId, marketId, canWrite, notify }) {
  const [data, setData] = useState(null); const [forms, setForms] = useState([]); const [formId, setFormId] = useState(""); const [busy, setBusy] = useState("");
  const load = async () => { try { const [questionResult, templateResult] = await Promise.all([api.getEventQuestions(dateId), api.getTemplates("onboarding")]); setData(questionResult); setForms(templateResult.templates); } catch (error) { notify(error.message, "err"); } };
  useEffect(() => { setData(null); load(); }, [dateId]);
  const apply = async () => { if (!formId) return notify("Choose an onboarding form", "err"); setBusy("apply"); try { await api.assignTemplate(Number(formId), { market_id: Number(marketId), market_date_id: Number(dateId) }); await load(); notify("Questions assigned to this event"); } catch (error) { notify(error.message, "err"); } finally { setBusy(""); } };
  const link = async (approval) => { setBusy(String(approval.id)); try { const result = await api.createAcknowledgmentLink(approval.id); const url = `${window.location.origin}/#/ack/${result.key}`; await navigator.clipboard?.writeText(url); notify("Vendor acknowledgment link copied"); } catch (error) { notify(error.message, "err"); } finally { setBusy(""); } };
  if (!data) return <div style={{ color: C.sub }} className="text-[13px] py-7"><Loader2 size={15} className="inline animate-spin mr-2" />Loading vendor questions…</div>;
  const questions = data.template?.config?.questions || [];
  return <div className="flex flex-col gap-4"><section style={{ background: C.card, border: `1px solid ${C.line}` }} className="rounded-2xl p-4"><p style={{ fontFamily: FD }} className="text-[19px] font-semibold">Vendor questions & acknowledgment</p><p style={{ color: C.sub }} className="text-[12.5px] mt-1">Vendors open their personal link, scroll through the questions, and submit their acknowledgment. Create forms in Templates → Onboarding Forms.</p>{!data.template && canWrite && <div className="flex flex-wrap gap-2 mt-3"><select value={formId} onChange={(event) => setFormId(event.target.value)} style={inp} className="min-w-56 px-3 py-2 rounded-lg text-[12px]"><option value="">Choose onboarding form…</option>{forms.map((form) => <option key={form.id} value={form.id}>{form.name}</option>)}</select><button onClick={apply} disabled={busy === "apply"} style={{ background: C.pine, color: "#fff" }} className="px-3 py-2 rounded-lg text-[12px] font-bold">Apply to this event</button></div>}{data.template && <div style={{ background: C.paper2 }} className="rounded-xl p-3 mt-3"><p className="text-[12.5px] font-bold">{data.template.name}</p><ol style={{ color: C.sub }} className="mt-2 pl-5 text-[12px] list-decimal flex flex-col gap-1">{questions.map((question) => <li key={question.id}>{question.label}</li>)}</ol></div>}</section>{data.template && <section className="flex flex-col gap-2">{data.approvals.length === 0 && <p style={{ color: C.faint }} className="text-center py-6 text-[13px]">Add vendors to this event before sending questions.</p>}{data.approvals.map((approval) => <article key={approval.id} style={{ background: C.card, border: `1px solid ${C.line}` }} className="rounded-xl p-3 flex items-center gap-3"><div className="flex-1"><p className="text-[13px] font-bold">{approval.business_name}</p><p style={{ color: C.sub }} className="text-[11.5px] capitalize">{approval.status.replaceAll("_", " ")}</p></div>{approval.acknowledged_at && <span style={{ background: C.sageSoft, color: C.pine }} className="px-2 py-1 rounded-full text-[10.5px] font-bold flex items-center gap-1"><CheckCircle2 size={12} /> Acknowledged</span>}{canWrite && <button onClick={() => link(approval)} disabled={busy === String(approval.id)} style={{ background: C.honeySoft, color: C.honeyDeep }} className="px-3 py-1.5 rounded-lg text-[11.5px] font-bold flex items-center gap-1"><Copy size={13} /> Copy vendor link</button>}</article>)}</section>}</div>;
}
