import React, { useEffect, useState } from "react";
import { Download, Loader2 } from "lucide-react";
import { api } from "./api";
import { C, FD } from "./theme";

const csv = (value) => `"${String(value ?? "").replaceAll('"', '""')}"`;
export default function EventDownloads({ dateId, approvals, notify }) {
  const [spots, setSpots] = useState(null);
  useEffect(() => { setSpots(null); api.getLayouts(dateId).then((result) => setSpots(result.layouts.flatMap((layout) => layout.spots || []))).catch((error) => notify(error.message, "err")); }, [dateId]);
  if (!spots) return <div style={{ color: C.sub }} className="py-7 text-[13px]"><Loader2 size={15} className="inline animate-spin mr-2" />Preparing vendor list…</div>;
  const spotByVendor = new Map(spots.filter((spot) => spot.vendor_id).map((spot) => [Number(spot.vendor_id), spot.code]));
  const rows = approvals.map((approval) => ({ vendor: approval.business_name, contact: approval.contact_name || "", email: approval.email || "", phone: approval.phone || "", spot: spotByVendor.get(Number(approval.vendor_id)) || "Unassigned", paid: approval.status === "paid", method: approval.payment_method || "", status: approval.status }));
  const download = () => { const header = ["Vendor", "Contact", "Email", "Phone", "Spot", "Paid", "Payment method", "Status"]; const data = rows.map((row) => [row.vendor, row.contact, row.email, row.phone, row.spot, row.paid ? "Yes" : "No", row.method, row.status]); const blob = new Blob([[header, ...data].map((row) => row.map(csv).join(",")).join("\n")], { type: "text/csv;charset=utf-8" }); const url = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = "markethub-event-vendors.csv"; anchor.click(); URL.revokeObjectURL(url); notify("Vendor list downloaded"); };
  return <div className="flex flex-col gap-4"><section style={{ background: C.card, border: `1px solid ${C.line}` }} className="rounded-2xl p-4 flex gap-3 items-center"><div className="flex-1"><p style={{ fontFamily: FD }} className="text-[19px] font-semibold">Vendor list download</p><p style={{ color: C.sub }} className="text-[12px] mt-1">Current vendors, assigned spot number, and paid/unpaid status for this event.</p></div><button onClick={download} style={{ background: C.pine, color: "#fff" }} className="px-3 py-2 rounded-lg text-[12px] font-bold flex items-center gap-1"><Download size={14} /> Download CSV</button></section><section style={{ background: C.card, border: `1px solid ${C.line}` }} className="rounded-2xl overflow-hidden"><div className="overflow-x-auto"><table className="w-full min-w-[620px] text-left"><thead style={{ background: C.paper2, color: C.sub }} className="text-[10.5px] uppercase"><tr>{["Vendor", "Spot", "Paid", "Method", "Status"].map((heading) => <th key={heading} className="px-4 py-3">{heading}</th>)}</tr></thead><tbody>{rows.map((row) => <tr key={row.vendor} style={{ borderTop: `1px solid ${C.line}` }} className="text-[12.5px]"><td className="px-4 py-3 font-semibold">{row.vendor}</td><td className="px-4 py-3 font-bold">{row.spot}</td><td className="px-4 py-3"><input type="checkbox" checked={row.paid} readOnly aria-label={`${row.vendor} paid`} /></td><td className="px-4 py-3 capitalize">{row.method || "—"}</td><td className="px-4 py-3 capitalize">{row.status.replaceAll("_", " ")}</td></tr>)}{rows.length === 0 && <tr><td colSpan="5" style={{ color: C.faint }} className="text-center px-4 py-8">No vendors are assigned to this event yet.</td></tr>}</tbody></table></div></section></div>;
}
